=== project-flogo/flogo-web/apps/server/src/modules/apps/schemas/full-app-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://github.com/TIBCOSoftware/flogo/schemas/1.0.0/full-app-schema.json",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "name",
    "type",
    "version",
    "triggers",
    "resources"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "default": "flogo:app"
    },
    "version": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "properties": {
      "type": "array",
      "items": {
        "ref": "common.json#/definitions/appProperty"
      }
    },
    "triggers": {
      "additionalProperties": false,
      "default": [],
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "ref": {
            "type": "string",
            "trigger-installed": true
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "settings": {
            "type": "object",
            "default": null
          },
          "handlers": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "actionId": {
                  "type": "string"
                },
                "settings": {
                  "type": "object",
                  "default": {}
                },
                "actionMappings": {
                  "input": {
                    "$ref": "#/definitions/MappingCollection"
                  },
                  "output": {
                    "$ref": "#/definitions/MappingCollection"
                  }
                }
              },
              "required": [
                "actionId",
                "settings"
              ]
            }
          }
        },
        "required": [
          "id",
          "ref",
          "settings",
          "handlers"
        ]
      }
    },
    "resources": {
      "default": [],
      "type": "array",
      "items": {
        "$ref": "#/definitions/ActionFlow"
      }
    }
  },
  "definitions": {
    "MappingCollection": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Mapping"
      }
    },
    "Mapping": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "integer"
        },
        "value": true,
        "mapTo": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "value",
        "mapTo"
      ]
    },
    "ActionMetadata": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "input": {
          "$ref": "#/definitions/ActionMetadata/definitions/AttributeCollection"
        },
        "output": {
          "$ref": "#/definitions/ActionMetadata/definitions/AttributeCollection"
        }
      },
      "definitions": {
        "AttributeCollection": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ActionMetadata/definitions/Attribute"
          }
        },
        "Attribute": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "type"
          ]
        }
      }
    },
    "ActionFlow": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "ref": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/ActionMetadata"
        },
        "data": {
          "type": "object",
          "properties": {
            "flow": {
              "$ref": "#/definitions/Flow"
            }
          }
        }
      },
      "required": [
        "id",
        "ref",
        "data"
      ]
    },
    "Flow": {
      "title": "flow",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "ref": {
          "type": "string"
        },
        "type": {
          "type": "integer"
        },
        "explicitReply": {
          "type": "boolean"
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Flow/definitions/attribute"
          }
        },
        "inputMappings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Flow/definitions/mapping"
          }
        },
        "rootTask": {
          "title": "rootTask",
          "$ref": "#/definitions/Flow/definitions/rootTask"
        },
        "errorHandlerTask": {
          "title": "errorHandlerTask",
          "$ref": "#/definitions/Flow/definitions/rootTask"
        }
      },
      "required": [
        "rootTask"
      ],
      "definitions": {
        "attribute": {
          "title": "attribute",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "enum": [
                "string",
                "integer",
                "int",
                "long",
                "number",
                "double",
                "boolean",
                "bool",
                "object",
                "array",
                "params",
                "any",
                "complexObject",
                "complex_object"
              ]
            },
            "value": {
              "type": [
                "string",
                "integer",
                "number",
                "boolean",
                "object",
                "array",
                "null"
              ]
            }
          },
          "required": [
            "name",
            "type",
            "value"
          ]
        },
        "mapping": {
          "title": "mapping",
          "type": "object",
          "properties": {
            "type": {
              "type": "integer"
            },
            "value": true,
            "mapTo": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "value",
            "mapTo"
          ]
        },
        "link": {
          "title": "link",
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "from": {
              "type": [
                "integer",
                "string"
              ]
            },
            "to": {
              "type": [
                "integer",
                "string"
              ]
            },
            "type": {
              "type": "integer"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "from",
            "to"
          ]
        },
        "task": {
          "title": "task",
          "type": "object",
          "properties": {
            "id": {
              "type": [
                "integer",
                "string"
              ]
            },
            "type": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "activityRef": {
              "type": "string",
              "activity-installed": true
            },
            "settings": {
              "title": "settings",
              "type": "object",
              "properties": {
                "iterate": {
                  "type": [
                    "string",
                    "integer"
                  ]
                },
                "flowPath": {
                  "type": "string"
                }
              }
            },
            "attributes": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/attribute"
              }
            },
            "inputMappings": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/mapping"
              }
            },
            "outputMappings": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/mapping"
              }
            },
            "tasks": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/task"
              }
            },
            "links": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/link"
              }
            }
          },
          "required": [
            "id"
          ],
          "if": {
            "properties": {
              "type": {
                "const": 4
              }
            }
          },
          "then": {
            "properties": {
              "settings": {
                "default": {},
                "required": [
                  "flowPath"
                ]
              }
            }
          },
          "else": {
            "required": [
              "activityRef"
            ],
            "if": {
              "properties": {
                "type": {
                  "const": 2
                }
              }
            },
            "then": {
              "properties": {
                "settings": {
                  "default": {},
                  "required": [
                    "iterate"
                  ]
                }
              }
            }
          }
        },
        "rootTask": {
          "title": "rootTask",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": [
                "integer",
                "string"
              ]
            },
            "type": {
              "type": "integer"
            },
            "attributes": {
              "type": "array",
              "default": [],
              "items": {
                "$ref": "#/definitions/Flow/definitions/attribute"
              }
            },
            "inputMappings": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/mapping"
              }
            },
            "outputMappings": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/mapping"
              }
            },
            "tasks": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/task"
              }
            },
            "links": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Flow/definitions/link"
              }
            }
          },
          "required": [
            "id"
          ]
        }
      }
    },
    "FlowEmbedded": {
      "type": "object",
      "properties": {
        "flow": {
          "$ref": "#/definitions/Flow"
        }
      },
      "required": [
        "flow"
      ]
    }
  }
}

=== project-flogo/flogo-web/apps/server/src/modules/transfer/tests/samples/legacy-app.json
{
  "name": "Test Application",
  "type": "flogo:app",
  "version": "0.0.1",
  "description": "",
  "triggers": [
    {
      "name": "Receive HTTP Message",
      "ref": "github.com/TIBCOSoftware/flogo-contrib/trigger/rest",
      "description": "Simple REST Trigger",
      "settings": {
        "port": null
      },
      "id": "receive_http_message",
      "handlers": [
        {
          "settings": {
            "method": null,
            "path": null,
            "autoIdReply": null,
            "useReplyHandler": null
          },
          "actionId": "test_flow",
          "actionMappings": {
            "input": [],
            "output": []
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "description": "ddadfads",
      "data": {
        "flow": {
          "name": "Test Flow",
          "type": 1,
          "attributes": [],
          "rootTask": {
            "id": "root",
            "type": 1,
            "tasks": [
              {
                "id": "log_2",
                "name": "Log Message",
                "description": "Simple Log Activity",
                "type": 1,
                "activityType": "tibco-log",
                "activityRef": "github.com/TIBCOSoftware/flogo-contrib/activity/log",
                "attributes": [
                  {
                    "name": "message",
                    "value": "Hello world",
                    "required": false,
                    "type": "string"
                  },
                  {
                    "name": "flowInfo",
                    "value": "true",
                    "required": false,
                    "type": "boolean"
                  },
                  {
                    "name": "addToFlow",
                    "value": "true",
                    "required": false,
                    "type": "boolean"
                  }
                ]
              }
            ],
            "links": [],
            "attributes": []
          }
        }
      },
      "id": "test_flow",
      "metadata": {
        "input": [
          {
            "name": "one",
            "type": "string"
          }
        ],
        "output": [
          {
            "name": "two",
            "type": "string"
          }
        ]
      },
      "ref": "github.com/TIBCOSoftware/flogo-contrib/action/flow"
    }
  ]
}
